# Generated by Django 4.2.2 on 2023-06-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.DateField(blank=True, null=True)),
                ('intensity', models.IntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=80, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('insight', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('impact', models.CharField(blank=True, max_length=200, null=True)),
                ('added', models.DateTimeField(blank=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('relevance', models.IntegerField(blank=True, null=True)),
                ('pestle', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('likelihood', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
